<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright © 2026 Petr Panteleyev -->
<!-- SPDX-License-Identifier: BSD-2-Clause -->
<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.panteleyev.stamps</groupId>
        <artifactId>stamps-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>stamps-client</artifactId>
    <packaging>jar</packaging>
    <name>Client Library</name>

    <dependencies>
        <dependency>
            <groupId>org.panteleyev.stamps</groupId>
            <artifactId>stamps-dto</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
        <dependency>
            <groupId>org.panteleyev</groupId>
            <artifactId>org-panteleyev-functional</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpecRootDirectory>${project.basedir}/../openapi</inputSpecRootDirectory>
                            <generatorName>java</generatorName>

                            <generateModels>false</generateModels>
                            <generateModelTests>false</generateModelTests>
                            <modelPackage>org.panteleyev.stamps.dto</modelPackage>

                            <generateApis>true</generateApis>
                            <generateApiTests>false</generateApiTests>
                            <apiPackage>org.panteleyev.stamps.client.openapi.api</apiPackage>

                            <invokerPackage>org.panteleyev.stamps.client.openapi.invoker</invokerPackage>

                            <typeMappings>
                                <typeMapping>string+uuid=UUID</typeMapping>
                                <typeMapping>string+date-time=LocalDateTime</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>UUID=java.util.UUID</importMapping>
                                <importMapping>LocalDateTime=java.time.LocalDateTime</importMapping>
                            </importMappings>

                            <configHelp>false</configHelp>

                            <library>native</library>

                            <generateSupportingFiles>true</generateSupportingFiles>
                            <supportingFilesToGenerate>
                                ApiClient.java,
                                Pair.java,
                                RFC3339JavaTimeModule.java,
                                RFC3339InstantDeserializer.java,
                                ApiResponse.java,
                                ApiException.java,
                                Configuration.java,
                                README.md,
                                ApiClient.java
                            </supportingFilesToGenerate>

                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <useJakartaEe>true</useJakartaEe>
                                <useBeanValidation>false</useBeanValidation>
                                <performBeanValidation>false</performBeanValidation>
                                <useTags>true</useTags>
                                <java17>true</java17>
                                <dateLibrary>java8</dateLibrary>
                                <serializationLibrary>jackson</serializationLibrary>
                                <useJspecify>true</useJspecify>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
