<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright © 2026 Petr Panteleyev -->
<!-- SPDX-License-Identifier: BSD-2-Clause -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <groupId>org.panteleyev.stamps</groupId>
    <artifactId>stamps-backend</artifactId>
    <version>${revision}</version>
    <name>Backend</name>

    <properties>
        <revision>26.9.3</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>26</java.version>
        <maven.compiler.release>26</maven.compiler.release>
        <!-- Plugins -->
        <buildHelperMavenPluginVersion>3.6.1</buildHelperMavenPluginVersion>
        <mavenResourcePluginVersion>3.4.0</mavenResourcePluginVersion>
        <mavenCompilerPluginVersion>3.16.0</mavenCompilerPluginVersion>
        <mavenJarPluginVersion>3.5.0</mavenJarPluginVersion>
        <mavenSurefirePluginVersion>3.5.4</mavenSurefirePluginVersion>
        <mavenFailSafePluginVersion>3.6.0-M1</mavenFailSafePluginVersion>
        <!--        <jpackageMavenPluginVersion>1.8.0</jpackageMavenPluginVersion>-->
        <openapiGeneratorMavenPluginVersion>7.23.0</openapiGeneratorMavenPluginVersion>
        <!-- Dependencies -->
        <postgresVersion>42.7.12</postgresVersion>
        <springDocsVersion>2.8.8</springDocsVersion>
        <restAssuredVersion>5.4.0</restAssuredVersion>
        <hamcrestVersion>2.2</hamcrestVersion>
        <testContainersVersion>2.0.5</testContainersVersion>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${testContainersVersion}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.rest-assured</groupId>
                <artifactId>rest-assured-common</artifactId>
                <version>${restAssuredVersion}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.panteleyev.stamps</groupId>
            <artifactId>stamps-dto</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-flyway</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springDocsVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-testcontainers</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${restAssuredVersion}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>xml-path</artifactId>
            <version>${restAssuredVersion}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapiGeneratorMavenPluginVersion}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpecRootDirectory>${project.basedir}/../openapi</inputSpecRootDirectory>
                            <generatorName>spring</generatorName>
                            <apiPackage>org.panteleyev.stamps.backend.openapi.api</apiPackage>
                            <generateModels>false</generateModels>
                            <generateModelTests>false</generateModelTests>
                            <modelPackage>org.panteleyev.stamps.dto</modelPackage>
                            <typeMappings>
                                <typeMapping>string+uuid=UUID</typeMapping>
                                <typeMapping>string+binary=StreamingResponseBody</typeMapping>
                                <typeMapping>string+date-time=LocalDateTime</typeMapping>
                            </typeMappings>
                            <importMappings>
                                <importMapping>UUID=java.util.UUID</importMapping>
                                <importMapping>
                                    StreamingResponseBody=org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody
                                </importMapping>
                                <importMapping>LocalDateTime=java.time.LocalDateTime</importMapping>
                            </importMappings>
                            <supportingFilesToGenerate>
                                ApiUtil.java
                            </supportingFilesToGenerate>
                            <configOptions>
                                <delegatePattern>true</delegatePattern>
                                <useSpringBoot3>true</useSpringBoot3>
                                <openApiNullable>false</openApiNullable>
                                <useBeanValidation>false</useBeanValidation>
                                <useResponseEntity>true</useResponseEntity>
                                <useTags>true</useTags>
                                <!--                                <useSwaggerUI>true</useSwaggerUI>-->
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${buildHelperMavenPluginVersion}</version>
                <executions>
                    <execution>
                        <id>add-integration-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/integration-test/java</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-integration-test-resource</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>src/integration-test/resources</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${mavenResourcePluginVersion}</version>
                <configuration>
                    <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${mavenCompilerPluginVersion}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${mavenJarPluginVersion}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${mavenSurefirePluginVersion}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${mavenFailSafePluginVersion}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.15</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <outputDirectory>${project.build.directory}/jar</outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!--            <plugin>-->
            <!--                <groupId>org.panteleyev</groupId>-->
            <!--                <artifactId>jpackage-maven-plugin</artifactId>-->
            <!--                <version>${jpackageMavenPluginVersion}</version>-->
            <!--                <configuration>-->
            <!--                    <name>Money Manager Backend</name>-->
            <!--                    <appVersion>${project.version}</appVersion>-->
            <!--                    <vendor>panteleyev.org</vendor>-->
            <!--                    <runtimeImage>${java.home}</runtimeImage>-->
            <!--                    <input>${project.build.directory}/jar</input>-->
            <!--                    <mainJar>money-manager-backend-${project.version}.jar</mainJar>-->
            <!--                    <mainClass>org.springframework.boot.loader.JarLauncher</mainClass>-->
            <!--                    <destination>target/dist</destination>-->
            <!--                </configuration>-->
            <!--                <executions>-->
            <!--                    <execution>-->
            <!--                        <id>linux</id>-->
            <!--                        <configuration>-->
            <!--                            <type>APP_IMAGE</type>-->
            <!--                        </configuration>-->
            <!--                    </execution>-->
            <!--                </executions>-->
            <!--            </plugin>-->
        </plugins>
    </build>

</project>
