openapi: "3.0.0"

info:
  title: Альбомы
  version: 1.0.0

tags:
  - name: 'albums, v1'
    description: 'Альбомы'

paths:
  /api/v1/albums:
    get:
      tags:
        - 'albums, v1'
      summary: 'Получить список альбомов'
      description: 'Получить полный список альбов в коллекции'
      operationId: getAlbums
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlbumDTO'
    post:
      tags:
        - 'albums, v1'
      summary: 'Создать альбом'
      operationId: postAlbum
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlbumDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/AlbumDTO'

  /api/v1/albums/{id}:
    delete:
      tags:
        - 'albums, v1'
      summary: 'Удалить альбом'
      operationId: deleteAlbum
      parameters:
        - name: id
          description: 'Идентификатор альбома'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: 'Success, no content'

    put:
      tags:
        - 'albums, v1'
      summary: 'Изменить альбом'
      operationId: putAlbum
      parameters:
        - name: id
          description: 'Идентификатор альбома'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlbumDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/AlbumDTO'

components:
  schemas:
    AlbumDTO:
      type: object
      required:
        - name
        - region
        - subalbums
      properties:
        id:
          type: string
          format: uuid
          description: 'Идентификатор альбома'
        name:
          type: string
          description: 'Название альбома'
          nullable: false
        region:
          type: string
          description: 'Регион альбома'
          nullable: false
        startYear:
          type: integer
          description: 'Начальный год альбома'
        endYear:
          type: integer
          description: 'Конечный год альбома'
        tags:
          type: array
          description: 'Теги в альбоме'
          items:
            type: string
        excludedTags:
          type: array
          description: 'Исключённые теги в альбоме'
          items:
            type: string
        subalbums:
          type: array
          description: 'Вложенные альбомы'
          nullable: false
          items:
            $ref: '#/components/schemas/AlbumDTO'
