openapi: '3.0.0'

info:
  title: Blocks
  version: 1.0.0

paths:
  /api/v1/blocks/{id}:
    get:
      tags:
        - 'blocks, v1'
      summary: 'Получить данные почтового блока'
      operationId: getBlock
      parameters:
        - name: id
          description: 'Идентификатор блока'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockDTO'
        "404":
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

    patch:
      tags:
        - 'blocks, v1'
      summary: 'Изменить данные почтового блока'
      operationId: patchBlock
      parameters:
        - name: id
          description: 'Идентификатор блока'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './objects.yml#/components/schemas/ItemPatchDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockDTO'
        "404":
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

components:
  schemas:

    BlockDTO:
      type: object
      description: 'Почтовый блок'
      required:
        - numberZag
        - description
        - stamps
        - tags
      allOf:
        - $ref: './objects.yml#/components/schemas/IssueItemDTO'
      properties:
        year:
          type: integer
          description: 'Год выпуска почтового блока'
        numberZag:
          type: integer
          description: 'Номер по каталогу Загорского'
          nullable: false
        numberCfa:
          type: integer
          description: 'Номер по каталогу ЦФА (для СССР)'
        denomination:
          type: number
          description: 'Номинал блока, если нет отдельных марок'
        description:
          type: string
          description: 'Описание почтового блока'
        stamps:
          type: array
          description: 'Марки в почтовом блоке'
          items:
            $ref: './stamps.yml#/components/schemas/StampDTO'
        tags:
          type: array
          description: 'Теги почтового блока'
          items:
            type: string
