openapi: '3.0.0'

info:
  title: Couplings
  version: 1.0.0

paths:
  /api/v1/couplings/{id}:
    get:
      tags:
        - 'couplings, v1'
      summary: 'Получить данные сцепки'
      operationId: getCoupling
      parameters:
        - name: id
          description: 'Идентификатор сцепки'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouplingDTO'
        "404":
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

    patch:
      tags:
        - 'couplings, v1'
      summary: 'Изменить данные сцепки'
      operationId: patchCoupling
      parameters:
        - name: id
          description: 'Идентификатор сцепки'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './objects.yml#/components/schemas/ItemPatchDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouplingDTO'
        "404":
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

components:
  schemas:
    CouplingDTO:
      type: object
      description: 'Сцепка марок'
      required:
        - stampNumbers
      allOf:
        - $ref: './objects.yml#/components/schemas/IssueItemDTO'
      properties:
        stampNumbers:
          type: array
          description: 'Номера марок, входящих в сцепку, по каталогу Загорского'
          nullable: false
          items:
            type: integer
