openapi: "3.0.0"

info:
  title: 'Выпуски почтовых марок'
  version: 1.0.0

paths:
  /api/v1/issues:
    get:
      tags:
        - 'issues, v1'
      summary: 'Получить список выпусков почтовых марок'
      operationId: getIssues
      parameters:
        - name: region
          description: 'Регион'
          in: query
          required: false
          schema:
            type: string
        - name: yearStart
          description: 'Первый год, включая'
          in: query
          required: false
          schema:
            type: integer
        - name: yearEnd
          description: 'Последний год, включая'
          in: query
          required: false
          schema:
            type: integer
        - name: tags
          description: 'Список тегов, через запятую'
          in: query
          required: false
          schema:
            type: string
        - name: excludedTags
          description: 'Список исключённых тегов, через запятую'
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IssueDTO'

    post:
      tags:
        - 'issues, v1'
      summary: 'Создать выпуск почтовых марок'
      operationId: postIssue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/IssueDTO'

  /api/v1/issues/{id}:
    delete:
      tags:
        - 'issues, v1'
      summary: 'Удалить выпуск почтовых марок'
      operationId: deleteIssue
      parameters:
        - name: id
          description: 'Идентификатор выпуска'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: 'Success, no content'

    put:
      tags:
        - 'issues, v1'
      summary: 'Изменить выпуск почтовых марок'
      operationId: putIssue
      parameters:
        - name: id
          description: 'Идентификатор выпуска'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/IssueDTO'

components:
  schemas:

    IssueDTO:
      type: object
      description: 'Выпуск почтовых марок'
      required:
        - title
        - region
        - date
        - stamps
        - blocks
        - couplings
      properties:
        id:
          type: string
          format: uuid
          description: 'Идентификатор выпуска'
        region:
          type: string
          description: 'Регион выпуска'
          nullable: false
        date:
          type: string
          format: date
          description: 'Дата выпуска'
          nullable: false
        title:
          type: string
          description: 'Название выпуска'
          nullable: false
        stamps:
          type: array
          description: 'Марки в выпуске'
          nullable: false
          items:
            $ref: './stamps.yml#/components/schemas/StampDTO'
        blocks:
          type: array
          description: 'Блоки в выпуске'
          nullable: false
          items:
            $ref: './blocks.yml#/components/schemas/BlockDTO'
        couplings:
          type: array
          description: 'Сцепки в выпуске'
          nullable: false
          items:
            $ref: './couplings.yml#/components/schemas/CouplingDTO'
