openapi: '3.0.0'

info:
  title: Objects
  version: 1.0.0

servers: []
paths: []

components:
  schemas:
    IssueItemDTO:
      type: object
      description: 'Базовые поля для марок, блоков и сцепок'
      reqiured:
        - hasClean
        - hasCancelled
        - replacementRequired
        - noPerforation
      properties:
        id:
          type: string
          format: uuid
          description: 'Идентификатор элемента'
        hasClean:
          type: boolean
          description: 'Коллекция содержит чистую марку, блок, сцепку'
          nullable: false
        hasCancelled:
          type: boolean
          description: 'Коллекция содержит гашёную марку, блок, сцепку'
          nullable: false
        replacementRequired:
          type: boolean
          description: 'Элемент нуждается в замене (например, поврежден)'
          nullable: false
        noPerforation:
          type: boolean
          description: 'Марка, блок или сцепка без перфорации'
          nullable: false
        comment:
          type: string
          description: 'Комментарий'

    ItemPatchDTO:
      type: object
      description: 'Patch for stamp, block or coupling'
      properties:
        hasClean:
          type: boolean
          description: 'Коллекция содержит чистую марку, блок, сцепку'
        hasCancelled:
          type: boolean
          description: 'Коллекция содержит гашёную марку, блок, сцепку'
        replacementRequired:
          type: boolean
          description: 'Элемент нуждается в замене (например, поврежден'

    ErrorDTO:
      type: object
      description: 'Сообщение об ошибке'
      required:
        - code
        - error
        - path
        - timestamp
      properties:
        code:
          type: integer
          description: 'Код ошибки'
          nullable: false
        error:
          type: string
          description: 'Сообщение'
          nullable: false
        path:
          type: string
          description: 'Путь запроса'
          nullable: false
        timestamp:
          type: string
          format: date-time
          description: 'Время ответа'
          nullable: false
