openapi: '3.0.0'

info:
  title: Регионы
  version: 1.0.0

paths:
  /api/v1/regions:
    get:
      tags:
        - 'regions, v1'
      summary: 'Получить список регионов'
      operationId: getRegions
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegionDTO'

    post:
      tags:
        - 'regions, v1'
      summary: 'Создать новый регион'
      operationId: postRegion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegionDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionDTO'
        "400":
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'
        "409":
          description: 'Conflict'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

components:
  schemas:

    RegionDTO:
      type: object
      description: 'Регион выпуска (РСФСР, СССР, Россия, etc.)'
      required:
        - name
        - startYear
      properties:
        id:
          type: string
          format: uuid
          description: 'Идентификатор региона'
          nullable: true
        name:
          type: string
          description: 'Название региона'
          nullable: false
        startYear:
          type: integer
          description: 'Год первого выпуска'
          nullable: false
        endYear:
          type: integer
          description: 'Год последнего выпуска'
          nullable: true
