openapi: '3.0.0'

info:
  title: Stamps
  version: 1.0.0

paths:
  /api/v1/stamps/{id}:
    get:
      tags:
        - 'stamps, v1'
      summary: 'Получить данные почтовой марки'
      operationId: getStamp
      parameters:
        - name: id
          description: 'Идентификатор почтовой марки'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampDTO'
        "404":
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

    patch:
      tags:
        - 'stamps, v1'
      summary: 'Изменить данные почтовой марки'
      operationId: patchStamp
      parameters:
        - name: id
          description: 'Идентификатор почтовой маркиp'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './objects.yml#/components/schemas/ItemPatchDTO'
      responses:
        "200":
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampDTO'
        "404":
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: './objects.yml#/components/schemas/ErrorDTO'

components:
  schemas:
    TestDTO:
      type: object
      properties:
        textField:
          type: string

    StampDTO:
      type: object
      description: 'Почтовая марка'
      required:
        - numberZag
        - denomination
        - description
        - tags
      allOf:
        - $ref: './objects.yml#/components/schemas/IssueItemDTO'
      properties:
        year:
          type: integer
          description: 'Год выпуска марки'
        numberZag:
          type: integer
          description: 'Номер по каталогу Загорского'
          nullable: false
        numberCfa:
          type: integer
          description: 'Номер по каталогу ЦФА (для СССР)'
        denomination:
          type: number
          description: 'Номинал марки'
          nullable: false
        description:
          type: string
          description: 'Описание'
          nullable: false
        blockNumber:
          type: integer
          description: 'Для марки в блоке номер блока по каталогу Загорского'
        tags:
          type: array
          description: 'Теги марки'
          nullable: false
          items:
            type: string
