spring:
  profiles:
    active: test
  application:
    name: @project.name@
    version: @project.version@
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
  flyway:
    locations:
      - classpath:db/init
      - classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /stamps

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

openapi:
  mergedSpec:
    base-path: /

logging:
  level:
    root: INFO
    org.panteleyev: DEBUG